package com.old.silence.mq.center.domain.model.permission;

import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import javax.persistence.Entity;
import java.math.BigInteger;

/**
 * 权限类型实体类
 * 对应数据库表：permission_type
 * 定义系统支持的所有权限类型（字典表）
 */
@Entity

public class PermissionType extends AbstractAutoGeneratedIdAuditable<BigInteger> {


    /**
     * 权限代码（唯一）
     * 例如：PRODUCE, CONSUME, CREATE_TOPIC
     */
    private String permissionCode;

    /**
     * 权限名称
     * 例如：生产消息、消费消息、创建Topic
     */
    private String permissionName;

    /**
     * 权限描述
     */
    private String description;

    /**
     * 权限状态
     * ACTIVE - 激活
     * INACTIVE - 禁用
     */
    private String status;

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public String getPermissionName() {
        return permissionName;
    }

    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
