package com.old.silence.mq.center.domain.model.permission;


import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import javax.persistence.Entity;
import java.math.BigInteger;

/**
 * 权限审计日志实体类
 * 对应数据库表：permission_audit_log
 * 记录所有权限相关的操作日志，用于审计和追踪
 */
@Entity
public class PermissionAuditLog extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 操作类型
     * REQUEST - 申请权限
     * APPROVE - 批准申请
     * REJECT - 拒绝申请
     * GRANT - 授予权限
     * REVOKE - 撤销权限
     * EXPIRE - 权限过期
     */
    private String operationType;

    /**
     * 操作人 ID
     */
    private BigInteger operatorId;

    /**
     * 操作人名称
     */
    private String operatorName;

    /**
     * 目标用户 ID
     */
    private BigInteger targetUserId;

    /**
     * 目标用户名
     */
    private String targetUserName;

    /**
     * Topic ID
     */
    private BigInteger topicId;

    /**
     * Topic 名称
     */
    private String topicName;

    /**
     * 权限代码
     */
    private String permissionCode;

    /**
     * 关联的权限申请 ID
     */
    private BigInteger requestId;

    /**
     * 操作详情（JSON 格式）
     */
    private String operationDetails;

    /**
     * 操作结果
     * SUCCESS - 成功
     * FAILED - 失败
     */
    private String operationResult;

    /**
     * 错误信息（仅在失败时）
     */
    private String errorMessage;

    /**
     * 操作人 IP 地址
     */
    private String ipAddress;

    public static Builder builder() {
        return new Builder();
    }

    public String getOperationType() {
        return operationType;
    }

    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    public BigInteger getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(BigInteger operatorId) {
        this.operatorId = operatorId;
    }

    public String getOperatorName() {
        return operatorName;
    }

    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    public BigInteger getTargetUserId() {
        return targetUserId;
    }

    public void setTargetUserId(BigInteger targetUserId) {
        this.targetUserId = targetUserId;
    }

    public String getTargetUserName() {
        return targetUserName;
    }

    public void setTargetUserName(String targetUserName) {
        this.targetUserName = targetUserName;
    }

    public BigInteger getTopicId() {
        return topicId;
    }

    public void setTopicId(BigInteger topicId) {
        this.topicId = topicId;
    }

    public String getTopicName() {
        return topicName;
    }

    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public BigInteger getRequestId() {
        return requestId;
    }

    public void setRequestId(BigInteger requestId) {
        this.requestId = requestId;
    }

    public String getOperationDetails() {
        return operationDetails;
    }

    public void setOperationDetails(String operationDetails) {
        this.operationDetails = operationDetails;
    }

    public String getOperationResult() {
        return operationResult;
    }

    public void setOperationResult(String operationResult) {
        this.operationResult = operationResult;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public static class Builder {
        private String operationType;
        private BigInteger operatorId;
        private String operatorName;
        private BigInteger targetUserId;
        private String targetUserName;
        private BigInteger topicId;
        private String topicName;
        private String permissionCode;
        private BigInteger requestId;
        private String operationDetails;
        private String operationResult;
        private String errorMessage;
        private String ipAddress;

        public Builder operationType(String operationType) {
            this.operationType = operationType;
            return this;
        }

        public Builder operatorId(BigInteger operatorId) {
            this.operatorId = operatorId;
            return this;
        }

        public Builder operatorName(String operatorName) {
            this.operatorName = operatorName;
            return this;
        }

        public Builder targetUserId(BigInteger targetUserId) {
            this.targetUserId = targetUserId;
            return this;
        }

        public Builder targetUserName(String targetUserName) {
            this.targetUserName = targetUserName;
            return this;
        }

        public Builder topicId(BigInteger topicId) {
            this.topicId = topicId;
            return this;
        }

        public Builder topicName(String topicName) {
            this.topicName = topicName;
            return this;
        }

        public Builder permissionCode(String permissionCode) {
            this.permissionCode = permissionCode;
            return this;
        }

        public Builder requestId(BigInteger requestId) {
            this.requestId = requestId;
            return this;
        }

        public Builder operationDetails(String operationDetails) {
            this.operationDetails = operationDetails;
            return this;
        }

        public Builder operationResult(String operationResult) {
            this.operationResult = operationResult;
            return this;
        }

        public Builder errorMessage(String errorMessage) {
            this.errorMessage = errorMessage;
            return this;
        }

        public Builder ipAddress(String ipAddress) {
            this.ipAddress = ipAddress;
            return this;
        }

        public PermissionAuditLog build() {
            PermissionAuditLog log = new PermissionAuditLog();
            log.operationType = this.operationType;
            log.operatorId = this.operatorId;
            log.operatorName = this.operatorName;
            log.targetUserId = this.targetUserId;
            log.targetUserName = this.targetUserName;
            log.topicId = this.topicId;
            log.topicName = this.topicName;
            log.permissionCode = this.permissionCode;
            log.requestId = this.requestId;
            log.operationDetails = this.operationDetails;
            log.operationResult = this.operationResult;
            log.errorMessage = this.errorMessage;
            log.ipAddress = this.ipAddress;
            return log;
        }
    }
}
