package com.old.silence.mq.center.domain.model.permission;

import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import javax.persistence.Entity;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * 权限申请实体类
 * 对应数据库表：permission_request
 * 记录用户的权限申请和审批历史
 */
@Entity
public class PermissionRequest extends AbstractAutoGeneratedIdAuditable<BigInteger> {


    /**
     * 申请用户 ID
     */
    private BigInteger userId;

    /**
     * 申请用户名
     */
    private String userName;

    /**
     * 涉及的 Topic ID（NULL 表示全局权限）
     */
    private BigInteger topicId;

    /**
     * Topic 名称（冗余字段，用于避免 JOIN）
     */
    private String topicName;

    /**
     * 权限类型 ID
     */
    private BigInteger permissionTypeId;

    /**
     * 权限代码
     * 例如：PRODUCE, CONSUME, CREATE_TOPIC
     */
    private String permissionCode;

    /**
     * 申请理由
     */
    private String requestReason;

    /**
     * 申请状态
     * PENDING - 待审批
     * APPROVED - 已批准
     * REJECTED - 已拒绝
     * EXPIRED - 已过期
     * WITHDRAWN - 已撤回
     */
    private String status;

    /**
     * 审批人 ID
     */
    private BigInteger approverId;

    /**
     * 审批人名称
     */
    private String approverName;

    /**
     * 审批意见
     */
    private String approvalReason;

    /**
     * 审批时间
     */
    private LocalDateTime approvalTime;

    /**
     * 权限过期时间（NULL 表示永久）
     */
    private LocalDateTime expireTime;

    public static Builder builder() {
        return new Builder();
    }

    public BigInteger getUserId() {
        return userId;
    }

    public void setUserId(BigInteger userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public BigInteger getTopicId() {
        return topicId;
    }

    public void setTopicId(BigInteger topicId) {
        this.topicId = topicId;
    }

    public String getTopicName() {
        return topicName;
    }

    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    public BigInteger getPermissionTypeId() {
        return permissionTypeId;
    }

    public void setPermissionTypeId(BigInteger permissionTypeId) {
        this.permissionTypeId = permissionTypeId;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public String getRequestReason() {
        return requestReason;
    }

    public void setRequestReason(String requestReason) {
        this.requestReason = requestReason;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public BigInteger getApproverId() {
        return approverId;
    }

    public void setApproverId(BigInteger approverId) {
        this.approverId = approverId;
    }

    public String getApproverName() {
        return approverName;
    }

    public void setApproverName(String approverName) {
        this.approverName = approverName;
    }

    public String getApprovalReason() {
        return approvalReason;
    }

    public void setApprovalReason(String approvalReason) {
        this.approvalReason = approvalReason;
    }

    public LocalDateTime getApprovalTime() {
        return approvalTime;
    }

    public void setApprovalTime(LocalDateTime approvalTime) {
        this.approvalTime = approvalTime;
    }

    public LocalDateTime getExpireTime() {
        return expireTime;
    }

    public void setExpireTime(LocalDateTime expireTime) {
        this.expireTime = expireTime;
    }

    public static class Builder {
        private BigInteger userId;
        private String userName;
        private BigInteger topicId;
        private String topicName;
        private BigInteger permissionTypeId;
        private String permissionCode;
        private String requestReason;
        private String status;
        private BigInteger approverId;
        private String approverName;
        private String approvalReason;
        private LocalDateTime approvalTime;
        private LocalDateTime expireTime;

        public Builder userId(BigInteger userId) {
            this.userId = userId;
            return this;
        }

        public Builder userName(String userName) {
            this.userName = userName;
            return this;
        }

        public Builder topicId(BigInteger topicId) {
            this.topicId = topicId;
            return this;
        }

        public Builder topicName(String topicName) {
            this.topicName = topicName;
            return this;
        }

        public Builder permissionTypeId(BigInteger permissionTypeId) {
            this.permissionTypeId = permissionTypeId;
            return this;
        }

        public Builder permissionCode(String permissionCode) {
            this.permissionCode = permissionCode;
            return this;
        }

        public Builder requestReason(String requestReason) {
            this.requestReason = requestReason;
            return this;
        }

        public Builder status(String status) {
            this.status = status;
            return this;
        }

        public Builder approverId(BigInteger approverId) {
            this.approverId = approverId;
            return this;
        }

        public Builder approverName(String approverName) {
            this.approverName = approverName;
            return this;
        }

        public Builder approvalReason(String approvalReason) {
            this.approvalReason = approvalReason;
            return this;
        }

        public Builder approvalTime(LocalDateTime approvalTime) {
            this.approvalTime = approvalTime;
            return this;
        }

        public Builder expireTime(LocalDateTime expireTime) {
            this.expireTime = expireTime;
            return this;
        }

        public PermissionRequest build() {
            PermissionRequest request = new PermissionRequest();
            request.userId = this.userId;
            request.userName = this.userName;
            request.topicId = this.topicId;
            request.topicName = this.topicName;
            request.permissionTypeId = this.permissionTypeId;
            request.permissionCode = this.permissionCode;
            request.requestReason = this.requestReason;
            request.status = this.status;
            request.approverId = this.approverId;
            request.approverName = this.approverName;
            request.approvalReason = this.approvalReason;
            request.approvalTime = this.approvalTime;
            request.expireTime = this.expireTime;
            return request;
        }
    }
}
