package com.old.silence.mq.center.domain.model.permission;

import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import javax.persistence.Column;
import javax.persistence.Entity;
import java.math.BigInteger;

/**
 * Topic 实体类
 * 对应数据库表：topic
 * 记录 RocketMQ 中存在的所有 Topic 元数据
 */
@Entity
public class Topic extends AbstractAutoGeneratedIdAuditable<BigInteger> {


    /**
     * Topic 名称（唯一）
     * 例如：Order-Topic, Payment-Topic
     */
    private String topicName;

    /**
     * 所属集群名称
     * 例如：DefaultCluster
     */
    private String clusterName;

    /**
     * Topic 描述
     */
    private String description;

    /**
     * 所有者用户 ID
     */
    private BigInteger ownerId;

    /**
     * 所有者名称
     */
    private String ownerName;

    /**
     * 是否系统 Topic
     * 0 = 普通 Topic
     * 1 = 系统 Topic
     */
    @Column(name = "is_system_topic")
    private Boolean systemTopic;

    /**
     * Topic 状态
     * ACTIVE - 激活
     * INACTIVE - 禁用
     * DELETED - 已删除
     */
    private String status;

    public String getTopicName() {
        return topicName;
    }

    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    public String getClusterName() {
        return clusterName;
    }

    public void setClusterName(String clusterName) {
        this.clusterName = clusterName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigInteger getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(BigInteger ownerId) {
        this.ownerId = ownerId;
    }

    public String getOwnerName() {
        return ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    public Boolean getSystemTopic() {
        return systemTopic;
    }

    public void setSystemTopic(Boolean systemTopic) {
        this.systemTopic = systemTopic;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
