package com.old.silence.mq.center.domain.model.permission;

import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * 用户权限实体类
 * 对应数据库表：user_permission
 * 存储已批准的、生效的用户权限（权限的最终映射）
 * <p>
 * 权限检查时直接查询此表，性能最优化
 */
@Entity
public class UserPermission extends AbstractAutoGeneratedIdAuditable<BigInteger> {


    /**
     * 用户 ID
     */
    private BigInteger userId;

    /**
     * 用户名
     */
    private String userName;

    /**
     * Topic ID（NULL 表示全局权限）
     */
    private BigInteger topicId;

    /**
     * Topic 名称（冗余字段，用于避免 JOIN）
     */
    private String topicName;

    /**
     * 权限类型 ID
     */
    private BigInteger permissionTypeId;

    /**
     * 权限代码
     * 例如：PRODUCE, CONSUME, CREATE_TOPIC
     */
    private String permissionCode;

    /**
     * 授权人 ID
     */
    private BigInteger grantedById;

    /**
     * 授权人名称
     */
    private String grantedByName;

    /**
     * 授权时间
     */
    private LocalDateTime grantedTime;

    /**
     * 权限过期时间（NULL 表示永久有效）
     */
    private LocalDateTime expireTime;

    /**
     * 是否已过期
     * 0 = 未过期
     * 1 = 已过期
     */
    @Column(name = "is_expired")
    private Boolean expired;

    /**
     * 权限状态
     * ACTIVE - 激活/有效
     * REVOKED - 已撤销
     * EXPIRED - 已过期
     */
    private String status;

    public static Builder builder() {
        return new Builder();
    }

    public BigInteger getUserId() {
        return userId;
    }

    public void setUserId(BigInteger userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public BigInteger getTopicId() {
        return topicId;
    }

    public void setTopicId(BigInteger topicId) {
        this.topicId = topicId;
    }

    public String getTopicName() {
        return topicName;
    }

    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    public BigInteger getPermissionTypeId() {
        return permissionTypeId;
    }

    public void setPermissionTypeId(BigInteger permissionTypeId) {
        this.permissionTypeId = permissionTypeId;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public BigInteger getGrantedById() {
        return grantedById;
    }

    public void setGrantedById(BigInteger grantedById) {
        this.grantedById = grantedById;
    }

    public String getGrantedByName() {
        return grantedByName;
    }

    public void setGrantedByName(String grantedByName) {
        this.grantedByName = grantedByName;
    }

    public LocalDateTime getGrantedTime() {
        return grantedTime;
    }

    public void setGrantedTime(LocalDateTime grantedTime) {
        this.grantedTime = grantedTime;
    }

    public LocalDateTime getExpireTime() {
        return expireTime;
    }

    public void setExpireTime(LocalDateTime expireTime) {
        this.expireTime = expireTime;
    }

    public Boolean getExpired() {
        return expired;
    }

    public void setExpired(Boolean expired) {
        this.expired = expired;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public static class Builder {
        private BigInteger userId;
        private String userName;
        private BigInteger topicId;
        private String topicName;
        private BigInteger permissionTypeId;
        private String permissionCode;
        private BigInteger grantedById;
        private String grantedByName;
        private LocalDateTime grantedTime;
        private LocalDateTime expireTime;
        private Boolean expired;
        private String status;

        public Builder userId(BigInteger userId) {
            this.userId = userId;
            return this;
        }

        public Builder userName(String userName) {
            this.userName = userName;
            return this;
        }

        public Builder topicId(BigInteger topicId) {
            this.topicId = topicId;
            return this;
        }

        public Builder topicName(String topicName) {
            this.topicName = topicName;
            return this;
        }

        public Builder permissionTypeId(BigInteger permissionTypeId) {
            this.permissionTypeId = permissionTypeId;
            return this;
        }

        public Builder permissionCode(String permissionCode) {
            this.permissionCode = permissionCode;
            return this;
        }

        public Builder grantedById(BigInteger grantedById) {
            this.grantedById = grantedById;
            return this;
        }

        public Builder grantedByName(String grantedByName) {
            this.grantedByName = grantedByName;
            return this;
        }

        public Builder grantedTime(LocalDateTime grantedTime) {
            this.grantedTime = grantedTime;
            return this;
        }

        public Builder expireTime(LocalDateTime expireTime) {
            this.expireTime = expireTime;
            return this;
        }

        public Builder expired(Boolean expired) {
            this.expired = expired;
            return this;
        }

        public Builder status(String status) {
            this.status = status;
            return this;
        }

        public UserPermission build() {
            UserPermission permission = new UserPermission();
            permission.userId = this.userId;
            permission.userName = this.userName;
            permission.topicId = this.topicId;
            permission.topicName = this.topicName;
            permission.permissionTypeId = this.permissionTypeId;
            permission.permissionCode = this.permissionCode;
            permission.grantedById = this.grantedById;
            permission.grantedByName = this.grantedByName;
            permission.grantedTime = this.grantedTime;
            permission.expireTime = this.expireTime;
            permission.expired = this.expired;
            permission.status = this.status;
            return permission;
        }
    }
}
