package com.old.silence.mq.center.domain.model;

import jakarta.persistence.Entity;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * 消费组监控阈值配置。
 */
@TableName("rmq_consumer_group_subcrible_record")
@Entity
public class ConsumerGroupSubscribeRecord extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private BigInteger userId;

    private BigInteger topicId;

    private String groupName;

    public BigInteger getUserId() {
        return userId;
    }

    public void setUserId(BigInteger userId) {
        this.userId = userId;
    }

    public BigInteger getTopicId() {
        return topicId;
    }

    public void setTopicId(BigInteger topicId) {
        this.topicId = topicId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
}