package com.old.silence.mq.center.domain.model;

import java.math.BigInteger;

import jakarta.persistence.Entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

/**
 * 消费组监控阈值配置。
 */
@TableName("rmq_consumer_monitor")
@Entity
public class ConsumerMonitor extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private String groupName;

    private Integer minCount;

    private Integer maxDiffTotal;

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Integer getMinCount() {
        return minCount;
    }

    public void setMinCount(Integer minCount) {
        this.minCount = minCount;
    }

    public Integer getMaxDiffTotal() {
        return maxDiffTotal;
    }

    public void setMaxDiffTotal(Integer maxDiffTotal) {
        this.maxDiffTotal = maxDiffTotal;
    }
}