package com.old.silence.mq.center.domain.model;


import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.handler.StringToMapHandler;
import com.old.silence.mq.center.enums.OperationType;

import java.math.BigInteger;
import java.util.Map;


@TableName("rmq_permission_audit_task")
@Entity
public class PermissionAuditTask extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 关联的权限申请 ID
     */
    private BigInteger requestId;

    private BigInteger dependsOnAuditTaskId;

    /**
     * 操作人名称
     */
    private String operatorName;


    private OperationType operationType;

    /**
     * 操作详情（JSON 格式）
     */
    @TableField(typeHandler = StringToMapHandler.class)
    private Map<String, Object> operationDetails;


    @ManyToOne
    @JoinColumn(name = "request_id", referencedColumnName = "id")
    private PermissionRequest permissionRequest;

    public BigInteger getRequestId() {
        return requestId;
    }

    public void setRequestId(BigInteger requestId) {
        this.requestId = requestId;
    }

    public BigInteger getDependsOnAuditTaskId() {
        return dependsOnAuditTaskId;
    }

    public void setDependsOnAuditTaskId(BigInteger dependsOnAuditLogId) {
        this.dependsOnAuditTaskId = dependsOnAuditLogId;
    }

    public String getOperatorName() {
        return operatorName;
    }

    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    public OperationType getOperationType() {
        return operationType;
    }

    public void setOperationType(OperationType operationType) {
        this.operationType = operationType;
    }

    public Map<String, Object> getOperationDetails() {
        return operationDetails;
    }

    public void setOperationDetails(Map<String, Object> operationDetails) {
        this.operationDetails = operationDetails;
    }

    public PermissionRequest getPermissionRequest() {
        return permissionRequest;
    }

    public void setPermissionRequest(PermissionRequest permissionRequest) {
        this.permissionRequest = permissionRequest;
    }
}
