package com.old.silence.mq.center.domain.model;

import jakarta.persistence.Entity;
import jakarta.persistence.OneToMany;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.mq.center.enums.PermissionStatus;

import java.math.BigInteger;
import java.time.Instant;
import java.util.List;


@TableName("rmq_permission_request")
@Entity
public class PermissionRequest extends AbstractAutoGeneratedIdAuditable<BigInteger> {


    /**
     * 申请人
     */
    private String applyName;

    /**
     * 权限类型 ID
     */
    private String permissionCode;

    /**
     * 申请理由
     */
    private String requestReason;

    /**
     * 申请状态
     * PENDING - 待审批
     * APPROVED - 已批准
     * REJECTED - 已拒绝
     * EXPIRED - 已过期
     * WITHDRAWN - 已撤回
     */
    private PermissionStatus status;

    /**
     * 权限过期时间
     */
    private Instant expireTime;

    @OneToMany(mappedBy = "permissionRequest")
    private List<PermissionAuditTask> permissionAuditTasks;

    public String getApplyName() {
        return applyName;
    }

    public void setApplyName(String applyName) {
        this.applyName = applyName;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public String getRequestReason() {
        return requestReason;
    }

    public void setRequestReason(String requestReason) {
        this.requestReason = requestReason;
    }

    public PermissionStatus getStatus() {
        return status;
    }

    public void setStatus(PermissionStatus status) {
        this.status = status;
    }
    public Instant getExpireTime() {
        return expireTime;
    }

    public void setExpireTime(Instant expireTime) {
        this.expireTime = expireTime;
    }

    public List<PermissionAuditTask> getPermissionAuditTasks() {
        return permissionAuditTasks;
    }

    public void setPermissionAuditTasks(List<PermissionAuditTask> permissionAuditTasks) {
        this.permissionAuditTasks = permissionAuditTasks;
    }
}
