package com.old.silence.mq.center.domain.model;

import jakarta.persistence.Entity;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.mq.center.enums.MessageType;
import com.old.silence.mq.center.enums.TopicStatus;

import java.math.BigInteger;

/**
 * Topic 实体类
 * 对应数据库表：topic
 * 记录 RocketMQ 中存在的所有 Topic 元数据
 */
@TableName("rmq_topic")
@Entity
public class Topic extends AbstractAutoGeneratedIdAuditable<BigInteger> {


    /**
     * Topic 名称（唯一）
     * 例如：Order-Topic, Payment-Topic
     */
    private String topicName;

    /**
     * Topic 描述
     */
    private String description;


    /**
     * 读队列数量
     */
    private int readQueueNums;

    /**
     * 写队列数量
     */
    private int writeQueueNums;

    /**
     * 消息类型 NORMAL, FIFO, DELAY, TRANSACTION
     */
    private MessageType messageType;


    /**
     * 是否系统 Topic
     * 0 = 普通 Topic
     * 1 = 系统 Topic
     */
    @TableField(value = "is_system_topic")
    private Boolean systemTopic;

    /**
     * Topic 状态
     * ACTIVE - 激活
     * INACTIVE - 禁用
     * DELETED - 已删除
     */
    private TopicStatus status;

    public String getTopicName() {
        return topicName;
    }

    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getReadQueueNums() {
        return readQueueNums;
    }

    public void setReadQueueNums(int readQueueNums) {
        this.readQueueNums = readQueueNums;
    }

    public int getWriteQueueNums() {
        return writeQueueNums;
    }

    public void setWriteQueueNums(int writeQueueNums) {
        this.writeQueueNums = writeQueueNums;
    }

    public MessageType getMessageType() {
        return messageType;
    }

    public void setMessageType(MessageType messageType) {
        this.messageType = messageType;
    }

    public Boolean getSystemTopic() {
        return systemTopic;
    }

    public void setSystemTopic(Boolean systemTopic) {
        this.systemTopic = systemTopic;
    }

    public TopicStatus getStatus() {
        return status;
    }

    public void setStatus(TopicStatus status) {
        this.status = status;
    }
}
