package com.old.silence.mq.center.domain.model;

import jakarta.persistence.Entity;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.mq.center.enums.PermissionStatus;

import java.math.BigInteger;
import java.time.Instant;


@TableName("rmq_user_permission")
@Entity
public class UserPermission extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 用户名
     */
    private String userName;

    /**
     * 权限代码
     * 例如：PRODUCE, CONSUME, CREATE_TOPIC
     */
    private String permissionCode;


    /**
     * 授权时间
     */
    private Instant grantedTime;

    /**
     * 权限过期时间（NULL 表示永久有效）
     */
    private Instant expireTime;

    /**
     * 是否已过期
     * 0 = 未过期
     * 1 = 已过期
     */
    @TableField(value = "is_expired")
    private Boolean expired;

    /**
     * 权限状态
     * ACTIVE - 激活/有效
     * REVOKED - 已撤销
     * EXPIRED - 已过期
     */
    private PermissionStatus status;


    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public Instant getGrantedTime() {
        return grantedTime;
    }

    public void setGrantedTime(Instant grantedTime) {
        this.grantedTime = grantedTime;
    }

    public Instant getExpireTime() {
        return expireTime;
    }

    public void setExpireTime(Instant expireTime) {
        this.expireTime = expireTime;
    }

    public Boolean getExpired() {
        return expired;
    }

    public void setExpired(Boolean expired) {
        this.expired = expired;
    }

    public PermissionStatus getStatus() {
        return status;
    }

    public void setStatus(PermissionStatus status) {
        this.status = status;
    }
}
